spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lesson_7
    username: login
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    change-log: classpath:db/changelog-master.xml
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp




server:
  servlet:
    context-path: /
